# Generated by Django 4.2.10 on 2024-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drink_tokens_used',
            field=models.IntegerField(default=0, help_text='Number of drink tokens used in this booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_tokens_used',
            field=models.IntegerField(default=0, help_text='Number of food tokens used in this booking'),
        ),
    ]
