# Generated by Django 4.2.10 on 2024-03-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_drink_tokens_used_booking_food_tokens_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='drink_items',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='drink_tokens_used',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='food_items',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='food_tokens_used',
        ),
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
