# Generated by Django 4.2.10 on 2024-07-20 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_drink_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
