# Generated by Django 4.2.10 on 2024-02-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('number_of_people', models.IntegerField(default=1)),
                ('playtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('drink_categories', models.ManyToManyField(limit_choices_to={'type': 'drink'}, related_name='drink_bundle', to='menu.category')),
                ('food_categories', models.ManyToManyField(limit_choices_to={'type': 'food'}, related_name='food_bundle', to='menu.category')),
            ],
        ),
    ]
