# Generated by Django 4.2.10 on 2024-03-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_bundle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='drink_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundle',
            name='food_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
