# Generated by Django 4.2.10 on 2024-03-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0004_bundle_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='categories',
        ),
        migrations.AddField(
            model_name='bundle',
            name='total_tokens',
            field=models.IntegerField(default=6),
        ),
    ]
