# Generated by Django 4.2.10 on 2024-03-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0006_bundle_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='drink_categories',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='drink_tokens',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='food_categories',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='food_tokens',
        ),
    ]
