# Generated by Django 4.2.10 on 2024-02-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_token_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', help_text='Specify whether this category is for food or drink.', max_length=5),
        ),
    ]
